### ISSUE TITLE
Obtain Sinograms

### ISSUE THREAD

**Issue by findme8** [RickHH/TransEM#1]
Hey,

I'm really interested in your work and would like to know how you generate sinogram datasets from raw PET datasets. Could you point me the code how you do that? Or do you have any recommendation on available python package I can use?

Thanks for your time!

**Comment by RickHH** [comment]
Hi,

The datasets and code were generated and modified based on the FBSEM paper (Andrew Reader 2020), here is the link of the code: https://github.com/Abolfazl-Mehranian/FBSEM/tree/master

Best

**Comment by findme8** [comment]
Thanks!

**Comment by findme8** [comment]
Sorry, one question: [https://github.com/RickHH/TransEM/blob/main/TransEM_train.py](https://github.com/RickHH/TransEM/blob/main/TransEM_train.py) line 14, is it okay to be empty? I found even at [https://github.com/Abolfazl-Mehranian/FBSEM/blob/master/build_training_sets.ipynb](https://github.com/Abolfazl-Mehranian/FBSEM/blob/master/build_training_sets.ipynb), I can't find system matrix path...

Thanks for your time!

**Comment by findme8** [comment]
Hey,

I have one another question: Where is RSTR code file here? Line 234 in [https://github.com/RickHH/TransEM/blob/main/modellib.py](https://github.com/RickHH/TransEM/blob/main/modellib.py).

Thanks!

**Comment by RickHH** [comment]
Updated with a simple version of RSTR
